import type { NextPage } from "next";
import Head from "next/head";
import { AuthSignInPage } from "components/pages/auth/AuthSignInPage";

const AuthSighIn: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ログイン</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthSignInPage />
    </div>
  );
};

export default AuthSighIn;
